"""empty message

Revision ID: 24b7c5d8e73d
Revises: ac3f8944b7ae
Create Date: 2024-09-27 17:05:55.475358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b7c5d8e73d'
down_revision = 'ac3f8944b7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authenticated', sa.Boolean(), nullable=True))
        batch_op.drop_column('authenicated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authenicated', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('authenticated')

    # ### end Alembic commands ###
