version: '3.12'

volumes:
  userapp:

services:
  user-service:
    container_name: user-service-c
    build:
      context: .
    ports:
      - "5001:5001"
    volumes:
      - userapp:/app
    restart: always
